apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: iot_home
    user: ${MYSQL_USER}
    secureJsonData:
      password: ${MYSQL_PASSWORD}
    isDefault: true
    editable: true
