path = 'C:\Espressif'
idf_path = 'C:\Espressif\v5.5.4\esp-idf'
esp_idf_json_path = 'C:\Espressif\tools'
tool_download_folder_name = 'C:\Espressif\dist'
tool_install_folder_name = 'C:\Espressif\tools'
target = ["esp32c6"]
idf_versions = ["v5.5.4"]
tools_json_file = "tools/tools.json"
config_file_save_path = 'F:\OneDrive\Documents\ChatGPT\闲时测试项目\tools\eim_config.toml'
non_interactive = true
wizard_all_questions = false
mirror = "https://dl.espressif.cn/github_assets"
idf_mirror = "https://gitee.com"
pypi_mirror = "https://pypi.tuna.tsinghua.edu.cn/simple"
recurse_submodules = false
install_all_prerequisites = true
repo_stub = "EspressifSystems/esp-idf"
skip_prerequisites_check = false
cleanup = false
skip_components_download = true
python_env_folder_name = "python"
activation_script_path_override = 'C:\Espressif\tools'
python_version_override = "python313"
create_bat_activation_script = false

[idf_features_per_version]
"v5.5.4" = ["core"]

[idf_tools_per_version]
"v5.5.4" = ["riscv32-esp-elf-gdb", "esp-clang", "esp-clang-libs", "riscv32-esp-elf", "cmake", "openocd-esp32", "ninja", "idf-exe", "ccache", "esp-rom-elfs"]
